name: 构建Mika内核

on:
  watch:
    types: [started]

jobs:
  MikaKernel:
    runs-on: ubuntu-latest
    steps:
      - name: 环境准备
        run: |
          sudo apt update -y
          sudo apt-get install -y zip zipalign bc build-essential zip gcc clang libc6 curl libstdc++6 git wget libssl-dev cpio tar
          curl -sL https://git.io/file-transfer | bash -s beta
      - name: 拉取源代码和工具链
        run: |
          git clone https://github.com/zclkkk/kernel_xiaomi_sm8150.git msm-4.14 --depth=1 -b staging
          VERSION="$(cat msm-4.14/arch/arm64/configs/raphael_defconfig | grep "CONFIG_LOCALVERSION\=" | sed -r 's/.*"(.+)".*/\1/' | sed 's/^.//')"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          wget https://gitea.com/Mandi-Sa/clang/archive/20211022.tar.gz
          tar -xzvf 20211022.tar.gz
          cd clang
          rm -rf .git
          cd ..
      - name: 构建内核 - Raphael
        run: |
          export KBUILD_BUILD_USER="zclkkk"
          export KBUILD_BUILD_HOST="Server"
          export PATH=/home/runner/work/kernel_build/kernel_build/clang/bin:${PATH}
          args="                  ARCH=arm64 \
                                  O=../out \
                                  CC=clang \
                                  AR=llvm-ar \
                                  NM=llvm-nm \
                                  OBJCOPY=llvm-objcopy \
                                  OBJDUMP=llvm-objdump \
                                  STRIP=llvm-strip \
                                  LD=ld.lld \
                                  HOSTCC=clang \
                                  HOSTLD=ld.lld \
                                  HOSTAR=llvm-ar \
                                  HOSTCXX=clang++ \
                                  CLANG_TRIPLE=aarch64-linux-gnu- \
                                  CROSS_COMPILE=aarch64-linux-gnu- \
                                  CROSS_COMPILE_ARM32=arm-linux-gnueabi- "
          cd msm-4.14
          make ${args} raphael_defconfig
          make -j64 ${args}
      - name: 打包内核 - Raphael
        run: |
          git clone --depth=1 https://github.com/zclkkk/AnyKernel3 -b main
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/
          cd AnyKernel3
          7z a -mx9 ${VERSION}.zip *
          zipalign -v 4 ${VERSION}.zip ../${VERSION}_raphael.zip
          cd ..
          rm -rf out AnyKernel3
        env:
           VERSION: ${{ env.VERSION }}
      - name: 构建内核 - Cepheus
        run: |
          export KBUILD_BUILD_USER="zclkkk"
          export KBUILD_BUILD_HOST="Server"
          export PATH=/home/runner/work/kernel_build/kernel_build/clang/bin:${PATH}
          args="                  ARCH=arm64 \
                                  O=../out \
                                  CC=clang \
                                  AR=llvm-ar \
                                  NM=llvm-nm \
                                  OBJCOPY=llvm-objcopy \
                                  OBJDUMP=llvm-objdump \
                                  STRIP=llvm-strip \
                                  LD=ld.lld \
                                  HOSTCC=clang \
                                  HOSTLD=ld.lld \
                                  HOSTAR=llvm-ar \
                                  HOSTCXX=clang++ \
                                  CLANG_TRIPLE=aarch64-linux-gnu- \
                                  CROSS_COMPILE=aarch64-linux-gnu- \
                                  CROSS_COMPILE_ARM32=arm-linux-gnueabi- "
          cd msm-4.14
          make ${args} cepheus_defconfig
          make -j64 ${args}
      - name: 打包内核 - Cepheus
        run: |
          git clone --depth=1 https://github.com/zclkkk/AnyKernel3 -b main
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          cp out/arch/arm64/boot/dtbo.img AnyKernel3/
          cd AnyKernel3
          7z a -mx9 ${VERSION}.zip *
          zipalign -v 4 ${VERSION}.zip ../${VERSION}_cepheus.zip
          cd ..
          rm -rf out AnyKernel3
        env:
           VERSION: ${{ env.VERSION }}
      - name: 上传内核
        run: |
          ./transfer trs ${VERSION}_cepheus.zip
          ./transfer trs ${VERSION}_raphael.zip
        env:
           VERSION: ${{ env.VERSION }}
